stages:
  - test
  #- version
  #- publish

include:
  ######################################  TESTING  ######################################
  - template: Security/SAST.gitlab-ci.yml

  # unit test
  - project: "lgensinger/cicd-templates"
    file: "node/module/test.yml"

  # coverage
  - project: "lgensinger/cicd-templates"
    file: "node/module/coverage.yml"

  ######################################  VERSIONING  ######################################

  # package
  #- project: "lgensinger/cicd-templates"
  #  file: "python/package/version.yml"

  ######################################  PUBLISHING  ######################################

  # pypi
  #- project: "lgensinger/cicd-templates"
  #  file: "python/package/publish.yml"
